//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotnet_tasks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dotnet_tasks.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] input {
            get {
                object obj = ResourceManager.GetObject("input", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id;Name;Description
        ///1;НПЗ№1;Первый нефтеперерабатывающий завод
        ///2;НПЗ№2;Второй нефтеперерабатывающий завод
        ///.
        /// </summary>
        internal static string input_factories {
            get {
                return ResourceManager.GetString("input_factories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id;Name;Description;FactoryId
        ///1;ГФУ-2;Газофракционирующая установка;1
        ///2;АВТ-6;Атмосферно-вакуумная трубчатка;1
        ///3;АВТ-10;Атмосферно-вакуумная трубчатка;2
        ///.
        /// </summary>
        internal static string input_tanks {
            get {
                return ResourceManager.GetString("input_tanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id;Name;Description;Volume;MaxVolume;UnitId
        ///1;Резервуар 1;Надземный - вертикальный;1500;2000;1
        ///2;Резервуар 2;Надземный - горизонтальный;2500;3000;1
        ///3;Дополнительный резервуар 24;Надземный - горизонтальный;3000;3000;2
        ///4;Резервуар 35;Надземный - вертикальный;3000;3000;2
        ///5;Резервуар 47;Подземный - двустенный;4000;5000;2
        ///6;Резервуар 256;Подводный;500;500;3
        ///.
        /// </summary>
        internal static string input_units {
            get {
                return ResourceManager.GetString("input_units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
